# Development Docker Compose with hot reload
# Usage: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

version: "3.8"

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - ENVIRONMENT=development
      - LOG_LEVEL=debug
    volumes:
      - ./backend/app:/app/app:ro
      - ./backend/storage:/app/storage
      - ./backend/logs:/app/logs
    ports:
      - "8000:8000"
